[package]
name = "oxipulse"
version = "0.3.10"
edition = "2024"
license = "Apache-2.0"
description = "Ultralight open source server monitoring agent"
repository = "https://github.com/securyblack/oxi-pulse"

[dependencies]
sb-agent-core = "0.1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
sysinfo = "0.33"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
opentelemetry = { version = "0.32", features = ["metrics"] }
opentelemetry_sdk = { version = "0.32", features = ["metrics", "rt-tokio"] }
opentelemetry-otlp = { version = "0.32", features = ["metrics", "grpc-tonic", "tls-ring", "tls-roots"] }
tonic = { version = "0.14", features = ["tls-ring", "tls-native-roots"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde_json = "1"
